name: Task2 Workflow

on:
  workflow_dispatch:
    inputs:
      manualTrigger:
        description: 'Trigger the workflow manually'
        required: true
        default: 'true'    

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "Hello World!"

