name: Task2 Workflow

# Extend your existing GitHub Actions workflow to include a [manual trigger].
#    - Inputs for manually triggered workflows are not needed, so you can skip them.

on:
  workflow_dispatch:
    inputs:
      manualTrigger:
        description: 'Trigger the workflow manually'
        required: true
        default: 'true'    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "Hello World!"

